#!/bin/bash
sudo grep 'dpi_mode=87' /boot/config.txt > /dev/null 2>&1
if [ $? -eq 0 ] ; then
echo "Il driver Video è impostato su VGA!"
sleep 4
echo "Conversione a JAMMA 15Khz"

sudo perl -p -i -e 's/#dpi_mode=87/dpi_mode=87/g' /boot/config.txt
sudo perl -p -i -e 's/#hdmi_timings=/hdmi_timings=/g' /boot/config.txt

echo "Modifiche effettuate! Spegnimento in corso!"
sleep 5
sudo halt
else
echo "Il driver video è già attivo!"
fi
